[0m08:19:05.435210 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001947BB57290>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001947BF5CEC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001947E5A4320>]}
[0m08:19:05.440209 [debug] [MainThread]: An error was encountered while trying to send an event


============================== 08:19:05.441209 | 8416be62-16dc-48b3-894c-78e316b64196 ==============================
[0m08:19:05.441209 [info ] [MainThread]: Running with dbt=1.9.5
[0m08:19:05.442207 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\yamin\\.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'invocation_command': 'dbt test', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m08:19:05.444207 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\yamin\OneDrive\Netflix_data\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m08:19:05.447339 [debug] [MainThread]: Command `dbt test` failed at 08:19:05.446330 after 0.21 seconds
[0m08:19:05.447339 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001947E4D8800>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001947BB57290>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001947EC6E3C0>]}
[0m08:19:05.448362 [debug] [MainThread]: An error was encountered while trying to send an event
[0m08:19:05.448362 [debug] [MainThread]: Flushing usage events
